use wtf_eat_db;

-- CREAR PROCEDIMIENTO ALMACENADO PARA INSERTAR UN CAMPO EN LA TABLA COMPANIAS
DROP PROCEDURE IF EXISTS SP_CREAR_NUEVA_COMPANIAS;

DECLARE DELIMITER $$
CREATE PROCEDURE SP_CREAR_NUEVA_COMPANIAS(  -- NOMBRE DEL PROCEDIMIENTO
		IN P_RAZONSOCIAL VARCHAR(100), -- PARAMETROS DE ENTRADA P_RAZONSOCIAL
        IN P_NOMBREMARCA VARCHAR(50), -- PARAMETROS DE ENTRADA P_NOMBRE_MARCA
        OUT VRESULT INT -- VRESULT COMO PARAMETRO DE SALIDA
        )

BEGIN -- INICIA E CUERPO DEL PROCEDIMIENTO
	
    DECLARE _ROLLBACK BOOL DEFAULT 0; -- DECLARA VARIABLE PARA MANEJAR EL ESTADO DE LOS ERRORES
    DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET _ROLLBACK = 1; -- ESTABLECE 1 SI HAY UN ERROR EN LA TRANSACCION
    
    START TRANSACTION; -- CUERPO DE LA TRANSACCION
		INSERT INTO COMPANIAS(RAZON_SOCIAL, NOMBRE_MARCA)
        VALUES(P_RAZONSOCIAL, P_NOMBREMARCA);
        SET VRESULT = 1;
    IF _ROLLBACK THEN
		ROLLBACK;
        SET VRESULT = -1;		
    ELSE
		COMMIT;
	END IF;    
END$$
DELIMITER ;


