

CREATE DATABASE WTF_EAT_DB;

USE WTF_EAT_DB;

-- COMPANIAS TABLE
CREATE TABLE COMPANIAS(
  RAZON_SOCIAL VARCHAR(100) NOT NULL,
  NOMBRE_MARCA VARCHAR(50),
  PRIMARY KEY (RAZON_SOCIAL)
); -- END COMPANIAS

-- PRODUCTOS TABLE
CREATE TABLE PRODUCTOS(
  ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(50) NOT NULL,
  TIPO VARCHAR(25),
  NOMBRE_COMPANIA VARCHAR(100),
  PRIMARY KEY(ID)
);

-- INGREDIENTES TABLE
CREATE TABLE INGREDIENTES(
  ID INT NOT NULL AUTO_INCREMENT,
  NOMBRE VARCHAR(100) NOT NULL,
  PRIMARY KEY(ID)
); -- END INGREDIENTES

-- PRODUCTO-INGREDIENTES TABLE
CREATE TABLE PRODUCTO_INGREDIENTES (
  ID_PRODUCTO INT,
  ID_INGREDIENTE INT,
  PRIMARY KEY(ID_PRODUCTO, ID_INGREDIENTE)
);
-- END PRODUCTO-INGREDIENTES TABLE

-- INFO_NUTRICIONALES TABLE
CREATE TABLE INFO_NUTRICIONALES(
  NOMBRE VARCHAR(50) NOT NULL,
  TIPO VARCHAR(50),
  PRIMARY KEY (NOMBRE)
);
-- END INFO_NUTRICIONALES TABLE

-- BALANCES TABLE
CREATE TABLE BALANCES(
  NUM_ITEM INT NOT NULL AUTO_INCREMENT,
  GRAMOS DECIMAL(3,3),
  PORCENTAJE_DIARIO SMALLINT(3),
  ID_PRODUCTO INT, 
  ID_INFO_NUTRICIONAL VARCHAR(50),
  PRIMARY KEY(NUM_ITEM)
);
-- END BALANCES TABLE

/*************FIN DE CREACIÓN TABLAS**********/
/*********************************************/
/********INICIO DE CREACION DE CONSTRAINTS PARA LLAVES FORANEAS******/
-- RELACIONAR PRODUCTOS CON COMPANIAS
ALTER TABLE PRODUCTOS
  ADD CONSTRAINT FK_PRODUCTOS_COMPANIA
    FOREIGN KEY (NOMBRE_COMPANIA) REFERENCES COMPANIAS(RAZON_SOCIAL) ON DELETE CASCADE;
-- FIN RELACIONAR PRODUCTOS CON COMPANIAS

-- RELACIONAR PRODUCTO_INGREDIENTES CON "PRODUCTOS" E "INGREDIENTES"
ALTER TABLE PRODUCTO_INGREDIENTES
  ADD CONSTRAINT FK_PRODUCTOS_INGREDIENTES_PROD
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE CASCADE;  
ALTER TABLE PRODUCTO_INGREDIENTES
  ADD CONSTRAINT FK_PRODUCTOS_INGREDIENTES_INGR
    FOREIGN KEY (ID_INGREDIENTE) REFERENCES INGREDIENTES(ID) ON DELETE CASCADE;

-- FIN RELACIONAR PRODUCTOS_INGREDIENTES CON "PRODUCTOS" E "INGREDIENTES"
    
-- RELACIONAR BALANCES CON "PROCUTOS" Y "INFO_NUTRICIONALES"
ALTER TABLE BALANCES  
  ADD CONSTRAINT FK_BALANCES_PROD
    FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID) ON DELETE CASCADE;
    
 ALTER TABLE BALANCES  
  ADD CONSTRAINT FK_BALANCES_INFONUTRI
    FOREIGN KEY (ID_INFO_NUTRICIONAL) REFERENCES INFO_NUTRICIONALES(NOMBRE) ON DELETE CASCADE;
-- END RELACIONAR BALANCES CON "PROCUTOS" Y "INFO_NUTRICIONALES"

